In [1]:
import numpy
a=numpy.array([1,2,3])

In [2]:
a

array([1, 2, 3])

In [3]:
l=[4,5,6]
b=numpy.array(l)

In [4]:
b

array([4, 5, 6])

In [5]:
c=numpy.arange(5)

In [6]:
c

array([0, 1, 2, 3, 4])

In [7]:
import numpy as np

In [44]:
d=np.arange(1,20,2)

In [9]:
d

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [10]:
e=np.ones(5)

In [11]:
e

array([1., 1., 1., 1., 1.])

In [13]:
f=np.zeros(5)
print(f)

[0. 0. 0. 0. 0.]


In [15]:
g=np.empty(7)
print(g)

[0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
 0.00000000e+00 0.00000000e+00 3.52610177e-57]


In [16]:
h=np.array([[1,2,3],[4,5,6]])
print(h)

[[1 2 3]
 [4 5 6]]


In [17]:
h[0]

array([1, 2, 3])

In [18]:
h[1]

array([4, 5, 6])

In [19]:
h[0,1]

2

In [20]:
h[0:]

array([[1, 2, 3],
       [4, 5, 6]])

In [21]:
i=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(i)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [22]:
i[0:1]

array([[1, 2, 3]])

In [23]:
i[0:1,1:2]

array([[2]])

In [25]:
i[0:2,0:2]

array([[1, 2],
       [4, 5]])

In [28]:
print(type(i))
print(i.dtype)

<class 'numpy.ndarray'>
int32


In [29]:
print(f.dtype)

float64


In [30]:
print(len(i))

3


In [31]:
print(len(a))

3


In [32]:
print(len(d))

10


In [33]:
print(i.ndim)

2


In [34]:
print(a.ndim)

1


In [1]:
import numpy as np
i=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(i)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [35]:
print(i.shape)

(3, 3)


In [2]:
import numpy
a=numpy.array([1,2,3])

In [3]:
a

array([1, 2, 3])

In [36]:
print(a.shape)

(3,)


In [4]:
h=np.array([[1,2,3],[4,5,6]])
print(h)

[[1 2 3]
 [4 5 6]]


In [37]:
print(h.shape)

(2, 3)


In [45]:
d

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [46]:
j=d.reshape(2,5)

In [47]:
j

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19]])

In [48]:
d

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [41]:
d.resize(5,2)

In [42]:
d

array([[ 1,  3],
       [ 5,  7],
       [ 9, 11],
       [13, 15],
       [17, 19]])

In [49]:
k=np.linspace(2,25,6)
print(k)

[ 2.   6.6 11.2 15.8 20.4 25. ]


In [51]:
l=a+b

In [52]:
l

array([5, 7, 9])

In [53]:
l-a

array([4, 5, 6])

In [54]:
m=a*b

In [55]:
m

array([ 4, 10, 18])

In [56]:
n=b/a
print(n)

[4.  2.5 2. ]


In [57]:
np.add(a,b)

array([5, 7, 9])

In [58]:
np.subtract(a,b)

array([-3, -3, -3])

In [59]:
np.multiply(a,b)

array([ 4, 10, 18])

In [60]:
np.divide(a,b)

array([0.25, 0.4 , 0.5 ])

In [61]:
np.dot(a,b)

32

In [62]:
a.sum()

6

In [63]:
i.sum()

45

In [64]:
i.mean()

5.0

In [65]:
i.avg()

AttributeError: 'numpy.ndarray' object has no attribute 'avg'

In [66]:
i.std()

2.581988897471611

In [67]:
i.var()

6.666666666666667

In [68]:
print(i)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [69]:
print(i.sum(axis=0))

[12 15 18]


In [70]:
print(i.sum(axis=1))

[ 6 15 24]


In [71]:
print(i.std(axis=0))

[2.44948974 2.44948974 2.44948974]


In [72]:
print(i.var(axis=0))

[6. 6. 6.]


In [73]:
print(i.var(axis=1))

[0.66666667 0.66666667 0.66666667]


In [74]:
print(i.mean(axis=0))

[4. 5. 6.]


In [75]:
n=np.arange(2,30,4)

In [76]:
n

array([ 2,  6, 10, 14, 18, 22, 26])

In [77]:
n+10

array([12, 16, 20, 24, 28, 32, 36])

In [78]:
n

array([ 2,  6, 10, 14, 18, 22, 26])

In [79]:
n-2

array([ 0,  4,  8, 12, 16, 20, 24])

In [80]:
n*2

array([ 4, 12, 20, 28, 36, 44, 52])

In [81]:
n

array([ 2,  6, 10, 14, 18, 22, 26])

In [82]:
n/2

array([ 1.,  3.,  5.,  7.,  9., 11., 13.])

In [83]:
n

array([ 2,  6, 10, 14, 18, 22, 26])

In [84]:
n[0],n[-1]

(2, 26)

In [87]:
n[0:3],n[-3:-1]

(array([ 2,  6, 10]), array([18, 22]))

In [92]:
a[[True,False,True]]

array([1, 3])

In [93]:
a[(a==0)|(a==1)]

array([1])

In [94]:
b[(b==0)|b==1]

array([], dtype=int32)

In [95]:
i[(i<=2)&(i%2==0)]

array([2])