In [1]:
import numpy as np

In [3]:
a=np.empty(5)

In [4]:
a

array([8.90104239e-307, 3.56050863e-307, 1.60219035e-306, 1.24610994e-306,
       9.45756549e-308])

In [5]:
print(np.sort(a))

[9.45756549e-308 3.56050863e-307 8.90104239e-307 1.24610994e-306
 1.60219035e-306]


In [11]:
b=np.arange(15)

In [7]:
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [13]:
c=b.reshape(3,5)

In [14]:
c

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [15]:
b

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [16]:
b=np.arange(15)

In [17]:
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [18]:
np.sum(b)

105

In [20]:
np.sum(c,axis=0)

array([15, 18, 21, 24, 27])

In [21]:
np.sum(c,axis=1)

array([10, 35, 60])